blank_issues_enabled: true
contact_links:
  - name: Open a Security Vulnerability Report
    url: https://github.com/piscinajs/piscina/security/advisories/new
    about: Do not open public issues that might have security implications. Report them privately here. See SECURITY.md.
