name: 'Documentation Build Test'
on:
  pull_request:
    paths:
      - docs/**

jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Use Node.js LTS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: docs/package.json

      - name: Install Dependencies
        run: |
          cd docs
          npm ci

      - name: build
        run: |
          cd docs
          npm run build
