name: 'Documentation'
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/current'
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Use Node.js LTS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: docs/package.json

      - name: Install Dependencies
        run: |
          cd docs
          yarn install --frozen-lockfile

      - name: build
        run: |
          cd docs
          yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: docs/build

  deploy:
    if: github.event.base_ref == 'refs/heads/current'
    permissions:
      pages: write
      id-token: write
    name: Deploy to GH Pages
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
