name: 'Documentation Build Test'
on:
  pull_request:
    paths:
      - docs/**

jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Use Node.js LTS
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: docs/package.json

      - name: Install Dependencies
        run: |
          cd docs
          npm ci

      - name: build
        run: |
          cd docs
          npm run build
