on:
  push:
    branches:
      - current

name: publish

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    if: >
      github.event.head_commit.author.username == 'github-actions[bot]' && github.event.head_commit.author.email == '41898282+github-actions[bot]@users.noreply.github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm install
      - run: npm publish --access public
