on:
  push:
    branches:
      - current

name: publish

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    if: >
      github.event.head_commit.author.username == 'github-actions[bot]' && github.event.head_commit.author.email == '41898282+github-actions[bot]@users.noreply.github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm install
      - run: npm publish --access public
